# Generated by Django 3.1 on 2020-08-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shipping to? Who is it for', max_length=120, null=True)),
                ('nickname', models.CharField(blank=True, help_text='Internal reference nickname', max_length=120, null=True)),
                ('address_type', models.CharField(choices=[('billing', 'Billing adress'), ('shipping', 'Shipping Address')], max_length=120)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('state', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=50)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile')),
            ],
        ),
    ]
